server:
  port: 8080
spring:
  application:
    name: acl-base
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      #    url: jdbc:mysql://10.0.16.6:3306/acl?useUnicode=true&characterEncoding=utf8&useSSL=false
      url: jdbc:mysql://42.192.37.49:3306/acl?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: owocloud
      password: 8Jp6G3EKscr9#!A&**
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 10
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，
      # 并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 6000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 180000
      # 用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query: select 'x'
      # 连接有效性检查的超时时间 1 秒
      validation-query-timeout: 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      #设置获取连接出错时的自动重连次数
      connection-error-retry-attempts: 1
      #设置获取连接时的重试次数，-1为不重试
      not-full-fimeout-retry-count: 2
      #重连间隔时间 单位毫秒
      acquire-retry-delay: 10000
      # 设置获取连接出错时是否马上返回错误，true为马上返回
      fail-fast: true
      #      超时时间限制，是否回收
      remove-abandoned: true
      #       超时时间
      remove-abandoned-timeout: 180
  redis:
    host: 101.35.146.86
    port: 8082
    password: 4redis@Invariable
    database: 1
    timeout: 500000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 20
        min-idle: 10
mybatis-plus:
  mapper-locations: mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印日志
wechat:
  mpAppId: wxbbd0694ba9ff514a
  mpAppSecret: e7f32b7689fa6e83602558c66da165d2
